# Gradle Settings
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=1.0.0
maven_group=org.chubby.github
archives_name=MobController
enabled_platforms=fabric,forge

# Minecraft Version
minecraft_version=1.20.1

# Architectury / Mappings
architectury_api_version=13.0.8
parchment_minecraft = 1.20.1
parchment_version=2023.09.03

# Fabric Dependencies
fabric_version=0.92.6+1.20.1
fabric_loader_version=0.16.14

# forge / Forge Dependencies
neo_form_version=1.21.1-20240808.144430
forge_version=47.4.0

# Optional Version Ranges and Loaders
minecraft_version_range=[1.20.1,1.21)
forge_loader_version_range=[1,)
forge_version_range=[47,)

# Java Settings
java_version=17

# Mod Metadata
mod_name=Mob Controller
mod_id=mobcontroller
mod_author = Small_chubby
mod_repo=https://github.com/AdarshKumarGit/MobController
mod_issues=https://github.com/AdarshKumarGit/MobController/issues
mod_license=MIT
mod_description=A mod that lets you control mobs.

# CurseForge Metadata
curse_project=1294574
curse_page=https://legacy.curseforge.com/minecraft/mc-mods/mobcontroller

# Modrinth Metadata
modrinth_project=hKIIpDgE
modrinth_page=https://modrinth.com/project/mobcontroller

# Dependencies
jei_version=15.2.0.27
crafttweaker_version=14.0.27